micronautVersion=5.0.5
zenithVersion=0.0.8

# SonarQube Project Configuration
systemProp.sonar.projectKey=pbu-projects_zenith
systemProp.sonar.organization=peanutbutter-unicorn
systemProp.sonar.projectName=zenith
systemProp.sonar.host.url=https://sonarcloud.io
systemProp.sonar.tests=src/test/groovy


